spring.application.name=teller-service
server.servlet.context-path=/apis/teller-service
server.port=8090
server.tomcat.max-http-header-size=65536
jwt.secret-key=7I1+k9fPbb02Lh4GxZZq9z6Me6GkqSfzFPQcMOqOsXA=
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


# MongoDB Configuration
spring.data.mongodb.uri=mongodb://my_teller:Teller2025@localhost:27017/my_teller?authMechanism=SCRAM-SHA-256
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.username=my_teller
spring.data.mongodb.password=Teller2025
spring.data.mongodb.database=my_teller
spring.h2.console.enabled=true
management.health.mongo.enabled=false



#
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=yourpassword
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=youralias
